name: First Work Flow
on: workflow_dispatch
jobs: 
 first-job: 
   runs-on: ubuntu-latest
   steps:
    - name: print greeting
      run: echo "Hello World!"
    - name: Print Good Bye
      run: echo "Done - bye!"
